# SwiftLint configuration

included:
  - Speak/Speak
  - Speak/Tests

excluded:
  - .build
  - build
  - DerivedData
  - Speak/.build

# Rule configuration
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  excluded:
    - i
    - j
    - x
    - y
    - z
    - a
    - b
    - id
    - fn

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - sorted_first_last
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_comma
  - todo
  - force_cast
  - large_tuple
